services:
  mariadb:
    container_name: mariadb
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: seriestrackerdb
      SPRING_DATASOURCE_USERNAME: root
      MARIADB_ROOT_PASSWORD: root
    # volumes:
    #  - ./mysql:/var/lib/mysql
    networks:
      - mariadb

networks:
  mariadb:
    driver: bridge


